[ gcp_service_account ]
type = "service_account"
project_id = "vasearchloggernew"
private_key_id = "15338f893dffda1ad07933da0edc2eea84ef59d6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFIo46QjW8hW3S
/uonLHYDGOLHqSxZwOF2/MHlaJGkEh2sfkCpJcxDk7fan7k+QdKYrW2SpVd6/MHn
Gqexx6EZYV9MvqSPG8T9/0iImg+A80AmNGmWzax+gFQcZwO0rAN3+yi+Ji5DuR/Y
yUw2jdmlVsElTIpG9jDCN4Nf936FBTP49bbOUlzBUKnZc3w3eCkLLutpl6EjJYHe
l1WZy0xyMJMgY2eQ8yTOALkEVO0FSVQmGTCZRx6e41uYEpNodZL/8B9LMaGdB8ot
KIrM3PdSQB0VqJS93HL953kmPz0kxE0nal4yiIj6xFWegPpKvBd5WqwzsxZwLG83
/avwcngtAgMBAAECggEAAvcS2BX8XG5OWVTbvUSaLtA+Qv4MrHnt+j3xhauVuzfJ
iflpLBIlOSP86TUrUmAnlIPRSNojT3aDTSBVwuMLjYftKMiaTYu/oglntCRLFOez
wI9bwjisPkfcXAQBpoNK1xBoS7njysF7VOWsN4rZKfc81vyIfOpBj/5JQ9WDaelE
EpzqyEwkHNbXjmFo2vFf2ccjCILZxxU7zTwBvWZQDB8AmDFa2QPxiTruDc1jxTV7
VVzHYCs+w4/CTxf8dGZrQ6WY5EuNsbUJoUV+0xSexcGsvwAC6Jj3XSs2vTdguYQ2
4hQ92HfktkIley+r6Y7rDFdoX42wwM0vdzNvf18UAQKBgQD7YQ+1GCMVrrfpyZqJ
ekYBHUHmFB4mG37DKZiQAGv8HBnRGn4HvyNGFPvbhPQyzMq5DB4hiN9pbHyq53UN
3WKfeoStqo0P/RIunO0bLDxH0xxDLgidRuOy6hBjoYDJSjgkw3uGEk9wb7BuN+zU
NYWUMFDOiqSNNkdXBVIziTvkAQKBgQDIwjt5s94DwBaq1qhCDQ8mZYVzBN4aw1jd
XCmQcx4kh2tMpw2urCUJ2lWfkEXk+xMkyIkNpjiW7VCVluSqxmIupqHn8vtxB5Ww
x1IzKZG52gyK2G4xWYc0xySxjUig8HFvRwJGxM+s7D4bpN4CDfw/Tl+0xIDrZSaq
HUUpX9tkLQKBgDzGwcpx9IGYhYSzpnZYprY8QaOD96oU+bfrxaQDRhhlHuTMd+4d
i0S1bBMt+PCTTOwifuJyujk97oJPhaB9hwuxzoRCeOqFsDCu5jCsqEJhSzL+3TxR
WFn4d0/vSzjfheV1kdbfdG9lwY1UXiEMc6hZaiAVqyUtG2Bxu+cT5fQBAoGAM8EW
0g4TewYHEe2anMR/FlfvqjIkC+Q2QYKj2HBE4gfjGnSqa1BHkB2wGx13V0t+qOnl
oxYp2oa9UoL+2iOgZgRhEsmqFn5tEZCg2T2rKq1StGyNI72/xFReWkNg6NRzectl
g9by7tJMRJYhAYiXcb6Dn7dUwNpnuE0pajwi89UCgYEArGGZcWS1LHIIX2k72DOt
Vk3gqpXTgtOHGlY+2TeKy8V0ZDXwmmPW8IHL5/WPloNvNy30Aid6bRLOd0Trv/gq
4Szl2MXqDiCIjXRuOYyV1Tak5j+C36O+BtAxhNLwL9qMWxFGqOr4bgsMbsdzNXTK
cckD6W4BbXeIqq0vR7OZXWE=
-----END PRIVATE KEY-----"""
client_email = "streamlit-logger-new@vasearchloggernew.iam.gserviceaccount.com"
client_id = "107791021502550752706"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-logger-new%40vasearchloggernew.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
